# Generated by Django 5.1 on 2024-08-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='anio',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediccion',
            name='periodo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
