# Generated by Django 5.1 on 2024-09-27 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0002_prediccion_anio_prediccion_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ponderacion', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prediccion',
            name='notas_materias',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicciones.materia')),
                ('prediccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicciones.prediccion')),
            ],
        ),
        migrations.AddField(
            model_name='prediccion',
            name='materias',
            field=models.ManyToManyField(through='predicciones.Nota', to='predicciones.materia'),
        ),
    ]
